web:
  - changed-files:
      - any-glob-to-any-file: web/**/*

api:
  - changed-files:
      - any-glob-to-any-file: api/**/*

data:
  - changed-files:
      - any-glob-to-any-file: data/**/*

project:
  - changed-files:
      - any-glob-to-any-file: data/models/projects/**/*

models:
  - changed-files:
      - any-glob-to-any-file: packages/models/**/*

utils:
  - changed-files:
      - any-glob-to-any-file: packages/utils/**/*

tooling:
  - changed-files:
      - any-glob-to-any-file: packages/tooling/**/*

repo:
  - changed-files:
      - any-glob-to-any-file: .github/**/*
