# This file drafts a release (e.g.: v6.1.2) each time a PR is merged
# Used by: .github/workflows/draft-new-release.yml

name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
tag-prefix: "v"
change-template: "- $TITLE by @$AUTHOR in #$NUMBER"
version-resolver:
  major:
    labels:
      - "breaking-change"
  minor:
    labels:
      - "feature"
      - "enhancement"
  default: patch
template: |
  [www.dzcode.io](https://www.dzcode.io)

  Join us on [Discord](https://discord.gg/TGbPsSMJC2)

  $CHANGES

autolabeler:
  - label: "breaking-change"
    body:
      - '/\- \[x\] Breaking change/'
  - label: "feature"
    body:
      - '/\- \[x\] New feature/'
  - label: "fix"
    body:
      - '/\- \[x\] Bug fix/'
