# This file is used by Github when clicking on "Generate Release Notes" in the "Releases" tab.
# We try to align it's content with .github/release-drafter.yml
# Used in case of manual release creation.

changelog:
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change

    - title: Features
      labels:
        - feature
        - enhancement

    - title: Bug fixes
      labels:
        - bug
        - bug-fix
        - bugfix
        - fix

    - title: Projects
      labels:
        - project

    - title: Other Changes
      labels:
        - "*"
