name-template: "stg-v$RESOLVED_VERSION"
tag-template: "stg-v$RESOLVED_VERSION"
tag-prefix: "stg-v"
include-pre-releases: true
prerelease: true
change-template: "- $TITLE (#$NUMBER)"
version-resolver:
  major:
    labels:
      - "breaking-change"
  minor:
    labels:
      - "feature"
  default: patch
template: |
  deploying `main` branch to stage:

  $CHANGES

  To test on `stage` environment go to:

  - [stage.dzcode.io](https://stage.dzcode.io)

autolabeler:
  - label: "breaking-change"
    body:
      - '/\- \[x\] Breaking change/'
  - label: "feature"
    body:
      - '/\- \[x\] New feature/'
  - label: "fix"
    body:
      - '/\- \[x\] Bug fix/'
