version: "3"
services:
  api:
    build: "."
    # restart: always
    ports:
      - "80:7070"
    env_file:
      - /home/ubuntu/app-env/api.env
    volumes:
      - /home/ubuntu/app-data/api/fetch_cache:/usr/src/repo/api/fetch_cache
      - /home/ubuntu/app-data/api/sqlite_db:/usr/src/repo/api/sqlite_db
