version: "3"
services:
  reverse-proxy:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - api
      - lhserver
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  api:
    build: "."
    ports:
      - "7070:7070"
    env_file:
      - /home/ubuntu/app-env/api.env
    volumes:
      - /home/ubuntu/app-data/api/fetch_cache:/usr/src/repo/api/fetch_cache
      - /home/ubuntu/app-data/api/sqlite_db:/usr/src/repo/api/sqlite_db
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - /home/ubuntu/app-data/api/postgres_db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: db
