name: Deploy To Stage Environment

on:
  push:
    tags:
      - "stg-v*"
  workflow_dispatch:

jobs:
  install-build-deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [20.x]
        os: [ubuntu-latest]

    env:
      CI: true
      STAGE: staging
      SSH_ADDRESS_STG: ${{ secrets.SSH_ADDRESS_STG }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      DEPLOY_VERSION: ${{ github.ref_type == 'tag' && github.ref_name || format('stg-0.0.0-{0}-{1}-{2}', github.ref_name, github.run_number, github.run_attempt) }}

    steps:
      - name: "Git"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "SSH"
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: "Nodejs"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: "Install"
        shell: bash
        run: |
          npm ci

      - name: "Bundle info"
        shell: bash
        run: |
          npm run generate:bundle-info $DEPLOY_VERSION stage

      - name: "Build"
        shell: bash
        run: |
          npm run build
          npx lerna run bundle:alone --scope @dzcode.io/web

      - name: "Sentry Release"
        shell: bash
        run: |
          npm run generate:sentry-release $DEPLOY_VERSION stage ${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: "Deploy"
        shell: bash
        run: |
          npm run deploy:stg
