on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      node-version:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ github.event.inputs.os }}
    steps:
      - name: "Git"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Nodejs"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ github.event.inputs.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build
