on:
  workflow_call:
    inputs:
      os-matrix:
        required: true
        type: string
        description: 'eg. ["macos-latest", "ubuntu-latest", "windows-latest"]'
      node-version-matrix:
        required: true
        type: string
        description: 'eg. ["20.x"]'

jobs:
  build:
    runs-on: ${{ github.event.inputs.os }}
    strategy:
      matrix:
        node-version: ${{ fromJson(github.event.inputs.node-version-matrix) }}
        os: ${{ fromJson(github.event.inputs.os-matrix) }}
      fail-fast: false
    steps:
      - name: "Git"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Nodejs"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ github.event.inputs.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build
