name: "CI Check for main Branch"

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/ci.reusable.build.yml
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        node-version: ["20"]
    with:
      node-version: ${{ matrix.node-version }}
      os: ${{ matrix.os }}

  test-coverage:
    needs: build
    uses: ./.github/workflows/ci.reusable.test-coverage.yml
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        node-version: ["20"]
    with:
      node-version: ${{ matrix.node-version }}
      os: ${{ matrix.os }}

  lint:
    needs: build
    uses: ./.github/workflows/ci.reusable.lint.yml
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        node-version: ["20"]
    with:
      node-version: ${{ matrix.node-version }}
      os: ${{ matrix.os }}

  misc:
    needs: build
    uses: ./.github/workflows/ci.reusable.misc.yml
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        node-version: ["20"]
    with:
      node-version: ${{ matrix.node-version }}
      os: ${{ matrix.os }}

  test-e2e:
    needs: build
    uses: ./.github/workflows/ci.reusable.test-e2e.yml
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        node-version: ["20"]
        # @TODO-ZM: add other browsers once we replace cypress with playwright
        browser: ["chrome"]
    with:
      node-version: ${{ matrix.node-version }}
      os: ${{ matrix.os }}
      browser: ${{ matrix.browser }}
