name: "CI Check for main Branch"

on:
  push:
    branches:
      - main

jobs:
  install-build-lint-test-coverage-misc:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [20.x]
        os: [macos-latest, ubuntu-latest, windows-latest]
      fail-fast: false

    steps:
      - name: "Git"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Nodejs"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: "Install"
        shell: bash
        run: |
          npm ci

      - name: "Build"
        shell: bash
        run: |
          npm run build

      - name: "Lint"
        shell: bash
        run: |
          npm run lint:alone

      - name: "Test"
        shell: bash
        run: |
          npm run test:alone  -- -- --coverage

      - name: "Misc"
        shell: bash
        run: |
          npx lerna run bundle:alone --scope @dzcode.io/web
          npx lerna run generate:sitemap --scope @dzcode.io/web
          npx lerna run generate:htmls --scope @dzcode.io/web

        env:
          CI: true
