name: "CI Check for PullRequest"

on:
  pull_request:

jobs:
  pr-labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: "Git"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true

  build:
    uses: ./.github/workflows/reusable/ci.build.yml
    with:
      node-version: "20"
      os: "ubuntu-latest"

  test-coverage:
    needs: build
    uses: ./.github/workflows/reusable/ci.test-coverage.yml
    with:
      node-version: "20"
      os: "ubuntu-latest"

  lint:
    needs: build
    uses: ./.github/workflows/reusable/ci.lint.yml
    with:
      node-version: "20"
      os: "ubuntu-latest"

  misc:
    needs: build
    uses: ./.github/workflows/reusable/ci.misc.yml
    with:
      node-version: "20"
      os: "ubuntu-latest"

  test-e2e:
    needs: build
    uses: ./.github/workflows/reusable/ci.test-e2e.yml
    with:
      node-version: "20"
      os: "ubuntu-latest"
