name: "CI Check for PullRequest"

on:
  pull_request:

jobs:
  # labels
  build:
    uses: ./.github/workflows/ci.build.yml
    with:
      node-version-matrix: '["20.x"]'
      os-matrix: '["macos-latest", "ubuntu-latest", "windows-latest"]'
  # lint
  # test
  # misc
