name: "CI End to End tests for PullRequest"

on:
  pull_request:

jobs:
  install-build-lint-test-misc:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [20.x]
        os: [ubuntu-latest]
        browser: [chrome, firefox, edge]
      fail-fast: false

    steps:
      - name: "Git"
        if: always()
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Nodejs"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: "Install"
        shell: bash
        run: |
          npm ci

      - name: "Cypress"
        uses: cypress-io/github-action@v5.5.1
        with:
          start: npm run dev:web
          wait-on: "http://localhost:8080"
          wait-on-timeout: 120
          browser: ${{ matrix.browser }}
          project: ./web

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: web/src/_e2e-test/screenshots

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: web/src/_e2e-test/videos
          retention-days: 1

        env:
          CI: true
