name: "CI Check for PullRequest"

on:
  pull_request:

jobs:
  # labels
  build:
    uses: ./.github/workflows/ci.build.yml
    with:
      node-version: "20"
      os: "ubuntu-latest"
  test-coverage:
    needs: build
    uses: ./.github/workflows/ci.test-coverage.yml
    with:
      node-version: "20"
      os: "ubuntu-latest"
  lint:
    needs: build
    uses: ./.github/workflows/ci.lint.yml
    with:
      node-version: "20"
      os: "ubuntu-latest"
  misc:
    needs: build
    uses: ./.github/workflows/ci.misc.yml
    with:
      node-version: "20"
      os: "ubuntu-latest"
