name: "CI Check for PullRequest"

on:
  pull_request:

jobs:
  # labels
  build:
    uses: ./.github/workflows/ci.build.yml
    with:
      node-version: "20"
      os: "ubuntu-latest"
  # lint
  # test
  # misc
