on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      node-version:
        required: true
        type: string

jobs:
  download-artifact-test-coverage:
    runs-on: ${{ inputs.os }}
    steps:
      - name: "Git"
        uses: actions/checkout@v4
      - name: "Nodejs"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dependencies and build output
      - run: npm install
      - run: npm run test:alone -- -- --coverage
